import type { Scheme, EmergencyContact, SchoolInfo, TouristPlace, CertificateService } from './types';

export const VILLAGE_INFO = {
  name: 'Gudlavalleru',
  name_te: 'గుడ్లవల్లేరు',
  name_hi: 'गुडलवल्लेरु',
  state: 'Andhra Pradesh',
  district: 'Krishna District',
  mandal: 'Gudlavalleru (Pamarru)',
  population: '11,400+',
  area: '12.5 sq.km',
  literacy: '78%',
  pincode: '521356',
  latitude: 16.3585,
  longitude: 81.0796,
  history: 'Gudlavalleru is a historic village and mandal headquarters in Krishna District, Andhra Pradesh. Located between Gudivada and Pamarru, it has long served as a local centre for trade, education, and agriculture in the Krishna delta region. The village is home to SRK Institute of Sciences and several colleges, making it an important educational hub in the mandal.',
  history_te: 'గుడ్లవల్లేరు ఆంధ్రప్రదేశ్‌లోని కృష్ణా జిల్లాలో ఒక చారిత్రక గ్రామం, మండల కేంద్రం. గుడివాడ మరియు పమర్రు మధ్య ఉన్న ఈ గ్రామం కృష్ణా డెల్టా ప్రాంతంలో వ్యాపార, విద్య మరియు వ్యవసాయానికి స్థానిక కేంద్రంగా ఉంది.',
  history_hi: 'गुडलवल्लेरु आंध्र प्रदेश के कृष्णा जिले में एक ऐतिहासिक गाँव और मंडल मुख्यालय है। गुडिवाड़ा और पमर्रु के बीच स्थित, यह कृष्णा डेल्टा क्षेत्र में व्यापार, शिक्षा और कृषि का केंद्र रहा है।',
  geography: 'Situated in the fertile Krishna delta, Gudlavalleru is surrounded by paddy fields and coconut groves. The land is well-irrigated by canals from the Krishna River, supporting multiple crops per year. The village is approximately 45 km from Vijayawada and 12 km from Gudivada.',
  geography_te: 'కృష్ణా డెల్టాలో ఉన్న గుడ్లవల్లేరు పచ్చిక పొలాలు మరియు కొబ్బరి తోటలతో చుట్టుముట్టబడి ఉంది. కృష్ణా నది కాలువల ద్వారా సాగు నీరు లభిస్తుంది.',
  geography_hi: 'कृष्णा डेल्टा में स्थित गुडलवल्लेरु धान के खेतों और नारियल के बगीचों से घिरा हुआ है। कृष्णा नदी की नहरों से सिंचाई होती है।',
  agriculture: 'Paddy (rice) is the primary crop, with two harvests per year. Other crops include black gram, green gram, sugarcane, and vegetables. Coconut and mango orchards are also common. Many farmers practice mixed farming with dairy and poultry.',
  agriculture_te: 'వరి ప్రధాన పంట. సంవత్సరానికి రెండు పంటలు. మినుము, పెసర, చెరకు, కూరగాయలు కూడా పండిస్తారు. కొబ్బరి మరియు మామిడి తోటలు సాధారణం.',
  agriculture_hi: 'धान मुख्य फसल है, साल में दो बार कटाई होती है। उड़द, मूंग, गन्ना और सब्जियाँ भी उगाई जाती हैं।',
  industries: 'Rice mills, oil mills, and small-scale agro-processing units form the main industry. The village also has retail markets, handloom, and brick-making units. The SRK Group of Institutions is a major employer and educational institution.',
  industries_te: 'వరి మిల్లులు, నూనె మిల్లులు ప్రధాన పరిశ్రమలు. చిన్న తరహా వ్యవసాయ ప్రాసెసింగ్ యూనిట్లు కూడా ఉన్నాయి.',
  industries_hi: 'चावल की मिलें और तेल की मिलें मुख्य उद्योग हैं। छोटे कृषि प्रसंस्करण इकाइयाँ भी हैं।',
  railway: 'Gudlavalleru Railway Station (GVA) lies on the Gudivada–Machilipatnam branch line. Passenger trains connect to Gudivada, Machilipatnam, and Vijayawada.',
  railway_te: 'గుడ్లవల్లేరు రైల్వే స్టేషన్ (GVA) గుడివాడ-మచిలీపట్నం శాఖ లైన్‌పై ఉంది.',
  railway_hi: 'गुडलवल्लेरु रेलवे स्टेशन (GVA) गुडिवाड़ा-मछलीपत्तनम शाखा लाइन पर स्थित है।',
  busStand: 'The APSRTC bus stand connects Gudlavalleru to Gudivada, Machilipatnam, Vijayawada, and surrounding villages with regular services.',
  busStand_te: 'ఏపీఎస్‌ఆర్‌టీసీ బస్ స్టాండ్ గుడ్లవల్లేరును గుడివాడ, మచిలీపట్నం, విజయవాడకు కలుపుతుంది.',
  busStand_hi: 'APSRTC बस स्टैंड गुडलवल्लेरु को गुडिवाड़ा, मछलीपत्तनम, विजयवाड़ा से जोड़ता है।',
};

export const GOVERNMENT_SCHEMES: Scheme[] = [
  {
    id: 'rythu-bharosa',
    title: 'YSR Rythu Bharosa',
    title_te: 'వైఎస్సార్ రైతు భరోసా',
    title_hi: 'वाईएसआर रैतु भरोसा',
    category: 'Agriculture',
    description: 'Financial assistance of ₹13,500 per year to farmer families, including landless farmers and tenant farmers, to support agricultural investment.',
    eligibility: 'All farmer families holding cultivable land in Andhra Pradesh. Landless SC/ST farmers and tenant farmers are also eligible.',
    documents: 'Aadhaar Card, Land Passbook (Patta), Bank Account Details, Passport Photo',
    benefits: '₹13,500 per year per family in three installments directly to bank account.',
    lastDate: 'Ongoing (Registered farmers receive it automatically)',
    applyLink: 'https://ssp.ap.gov.in/',
    helpline: '1900',
    steps: [
      'Visit the nearest Grama Sachivalayam or Rythu Bharosa Kendram (RBK)',
      'Submit Aadhaar, Land Passbook, and bank details',
      'Verification by Village Volunteer and Agriculture Assistant',
      'Approval at Mandal level',
      'Amount credited directly to bank account in 3 installments',
    ],
    tags: ['Agriculture', 'Financial Aid', 'Farmers'],
  },
  {
    id: 'ysr-asara',
    title: 'YSR Aasara',
    title_te: 'వైఎస్సార్ ఆసర',
    title_hi: 'वाईएसआर आसरा',
    category: 'Women Welfare',
    description: 'Interest-free loans and financial support to women self-help groups (SHGs) to promote small businesses and entrepreneurship.',
    eligibility: 'Women members of registered SHGs (Self Help Groups) in Andhra Pradesh.',
    documents: 'Aadhaar Card, SHG Membership Details, Bank Account, White Ration Card',
    benefits: 'Interest-free loans up to ₹25,000 per member, payable in easy installments.',
    lastDate: 'Ongoing (through SHG federations)',
    applyLink: 'https://serp.ap.gov.in/',
    helpline: '1902',
    steps: [
      'Contact your SHG group leader or Community Organizer',
      'Ensure your SHG is registered with SERP',
      'Submit member Aadhaar and bank details to the federation',
      'Loan amount disbursed to SHG group account',
      'Repay in easy monthly installments — no interest charged',
    ],
    tags: ['Women', 'Loans', 'SHG'],
  },
  {
    id: 'navaratnalu-housing',
    title: 'YSR Housing Scheme (Navaratnalu)',
    title_te: 'వైఎస్సార్ గృహ పథకం',
    title_hi: 'वाईएसआर आवास योजना',
    category: 'Housing',
    description: 'Free or subsidized pucca houses for eligible poor families who do not own a house. Beneficiaries receive a house site and financial assistance for construction.',
    eligibility: 'Families below poverty line without a pucca house. Priority to SC, ST, and differently-abled beneficiaries.',
    documents: 'Aadhaar Card, Income Certificate, Caste Certificate, Bank Passbook, Voter ID',
    benefits: 'House site pattas and construction assistance of up to ₹2.5 lakh.',
    lastDate: 'Ongoing (apply at Gram Sachivalayam)',
    applyLink: 'https://housing.ap.gov.in/',
    helpline: '1902',
    steps: [
      'Apply at Grama Sachivalayam with income and caste certificates',
      'Field verification by Village Surveyor',
      'Beneficiary list displayed at Panchayat office',
      'House site patta allotted after approval',
      'Construction assistance released in phases',
    ],
    tags: ['Housing', 'BPL', 'Construction'],
  },
  {
    id: 'ysr-health',
    title: 'YSR Aarogyasri Health Insurance',
    title_te: 'వైఎస్సార్ ఆరోగ్యశ్రీ',
    title_hi: 'वाईएसआर आरोग्यश्री',
    category: 'Healthcare',
    description: 'Free medical treatment up to ₹5 lakh per family per year for serious illnesses at empanelled hospitals.',
    eligibility: 'All families holding the YSR Aarogyasri Health Card. Based on income and white ration card.',
    documents: 'Aadhaar Card, White Ration Card, Aarogyasri Card',
    benefits: 'Cashless treatment up to ₹5 lakh/year covering 2,000+ medical procedures.',
    lastDate: 'Ongoing (enroll at Village Volunteer / Grama Sachivalayam)',
    applyLink: 'https://www.ysraarogyasri.ap.gov.in/',
    helpline: '1900',
    steps: [
      'Visit Grama Sachivalayam with White Ration Card and Aadhaar',
      'Enrollment and biometric verification',
      'Receive YSR Aarogyasri Health Card',
      'Use card at any empanelled hospital for cashless treatment',
      'No out-of-pocket expenses for covered procedures',
    ],
    tags: ['Health', 'Insurance', 'Free Treatment'],
  },
  {
    id: 'ambedkar-vidyadeevena',
    title: 'YSR Vidya Deevena (Fee Reimbursement)',
    title_te: 'వైఎస్సార్ విద్యా దీవెన',
    title_hi: 'वाईएसआर विद्या दीवेना',
    category: 'Scholarships',
    description: 'Full fee reimbursement for students from poor families pursuing higher education (degree, engineering, medical, polytechnic).',
    eligibility: 'Students from SC/ST/BC/Minority/EBC and Kapu categories with family income below ₹2.5 lakh/year.',
    documents: 'Aadhaar Card, Income Certificate, Caste Certificate, Bonafide/Study Certificates, Bank Account',
    benefits: 'Full tuition fee + ₹20,000 maintenance allowance per year.',
    lastDate: 'Apply within 30 days of admission (JNTUK/AP online)',
    applyLink: 'https://jnanabhumi.ap.gov.in/',
    helpline: '1902',
    steps: [
      'Register on Jnanabhumi portal after admission',
      'Upload income certificate, caste certificate, and study certificates',
      'College principal verifies and approves application',
      'Tuition fee paid directly to college by government',
      'Maintenance allowance credited to student bank account',
    ],
    tags: ['Education', 'Scholarship', 'Students'],
  },
  {
    id: 'ysr-pension',
    title: 'YSR Pension Kanuka',
    title_te: 'వైఎస్సార్ పెన్షన్ కనుక',
    title_hi: 'वाईएसआर पेंशन कनुका',
    category: 'Pension Schemes',
    description: 'Monthly pension of ₹3,000 for old age, widows, weavers, toddy tappers, fishermen, and differently-abled persons.',
    eligibility: 'Persons aged 60+ (old age), widows, differently-abled (40%+ disability), single women, and other eligible categories.',
    documents: 'Aadhaar Card, Age Proof, Income Certificate, Disability Certificate (if applicable), Bank Passbook',
    benefits: '₹3,000 per month directly to bank account.',
    lastDate: 'Ongoing (apply at Gram Sachivalayam)',
    applyLink: 'https://gramasachivalayam.ap.gov.in/',
    helpline: '1902',
    steps: [
      'Visit Grama Sachivalayam with age proof and Aadhaar',
      'Fill pension application form with category details',
      'Verification by Village Volunteer',
      'Approval by Mandal Parishad Development Officer',
      'Monthly pension credited to bank account every month',
    ],
    tags: ['Pension', 'Senior Citizens', 'Welfare'],
  },
  {
    id: 'yuvanestam',
    title: 'Mukhyamantri Yuvanestam (Unemployment Allowance)',
    title_te: 'ముఖ్యమంత్రి యువనెస్తం',
    title_hi: 'मुख्यमंत्री युवनेस्तम',
    category: 'Employment',
    description: 'Monthly unemployment allowance of ₹1,000 to eligible educated unemployed youth to support job search.',
    eligibility: 'Unemployed youth aged 22-35 with degree/diploma, family income below ₹3 lakh/year.',
    documents: 'Aadhaar Card, Educational Qualification Certificates, Income Certificate, Bank Account',
    benefits: '₹1,000 per month until employment.',
    lastDate: 'Ongoing (apply online)',
    applyLink: 'https://appsc.ap.gov.in/',
    helpline: '1902',
    steps: [
      'Register on the APPSC portal with educational qualifications',
      'Upload degree/diploma certificates and income certificate',
      'Verification by employment exchange',
      'Approval and enrollment in beneficiary list',
      'Monthly allowance credited to bank account',
    ],
    tags: ['Employment', 'Youth', 'Allowance'],
  },
  {
    id: 'sukhibhava',
    title: 'YSR Sunna Vaddi (Zero Interest on Crop Loans)',
    title_te: 'వైఎస్సార్ సున్నా వడ్డీ',
    title_hi: 'वाईएसआर सुन्ना वड्डी',
    category: 'Agriculture',
    description: 'Interest subvention on crop loans — farmers who repay on time get the interest amount reimbursed, making the loan effectively interest-free.',
    eligibility: 'Farmers who avail crop loans from banks and repay within the due date.',
    documents: 'Aadhaar Card, Land Passbook, Crop Loan Account Details',
    benefits: 'Interest reimbursement up to ₹1.5 lakh loan amount per farmer.',
    lastDate: 'Ongoing (auto-credited on timely repayment)',
    applyLink: 'https://ssp.ap.gov.in/',
    helpline: '1900',
    steps: [
      'Avail crop loan from your bank using land passbook',
      'Repay the loan amount within the due date',
      'Interest amount automatically reimbursed to your account',
      'No separate application needed for existing crop loan borrowers',
      'Check bank statement for interest subvention credit',
    ],
    tags: ['Agriculture', 'Crop Loan', 'Interest-Free'],
  },
  {
    id: 'pm-kisan',
    title: 'PM-KISAN Samman Nidhi',
    title_te: 'పీఎం-కిసాన్ సమ్మాన్ నిధి',
    title_hi: 'पीएम-किसान सम्मान निधि',
    category: 'Agriculture',
    description: 'Central government scheme providing ₹6,000 per year to all landholding farmer families in three equal installments.',
    eligibility: 'All landholding farmer families with cultivable land. Institutional farmers, income taxpayers, and serving/retired government employees are excluded.',
    documents: 'Aadhaar Card, Land Records (Patta), Bank Account Details',
    benefits: '₹6,000 per year in 3 installments of ₹2,000 each, directly to bank account.',
    lastDate: 'Ongoing (apply online or at Common Service Center)',
    applyLink: 'https://pmkisan.gov.in/',
    helpline: '1800115526',
    steps: [
      'Visit pmkisan.gov.in or nearest Common Service Center (CSC)',
      'Enter Aadhaar number and land details',
      'Verification by State Nodal Officer',
      'Name appears in beneficiary list after approval',
      '₹2,000 credited every 4 months to bank account',
    ],
    tags: ['Agriculture', 'Central Govt', 'Financial Aid'],
  },
  {
    id: 'jeevan',
    title: 'PM Jeevan Jyoti Bima Yojana',
    title_te: 'పీఎం జీవన్ జ్యోతి బీమా యోజన',
    title_hi: 'पीएम जीवन ज्योति बीमा योजना',
    category: 'Insurance',
    description: 'Life insurance cover of ₹2 lakh at a premium of just ₹436 per year, available to all bank account holders aged 18-50.',
    eligibility: 'Savings bank account holders aged 18 to 50 years. Must have auto-debit enabled.',
    documents: 'Aadhaar Card, Bank Passbook, PP (Pradhan Mantri) declaration form',
    benefits: '₹2 lakh life cover for natural or accidental death. Premium only ₹436/year.',
    lastDate: 'Enroll before May 31 each year',
    applyLink: 'https://www.jansuraksha.gov.in/',
    helpline: '180018011125',
    steps: [
      'Visit your bank branch with Aadhaar and passbook',
      'Fill the PMJJBY consent form for auto-debit',
      'Premium of ₹436 auto-debited from account each year',
      '₹2 lakh paid to nominee in case of death',
      'Continue coverage by maintaining sufficient balance',
    ],
    tags: ['Insurance', 'Life Cover', 'Low Premium'],
  },
  {
    id: 'suraksha',
    title: 'PM Suraksha Bima Yojana',
    title_te: 'పీఎం సురక్ష బీమా యోజన',
    title_hi: 'पीएम सुरक्षा बीमा योजना',
    category: 'Insurance',
    description: 'Accidental insurance cover of ₹2 lakh at a premium of just ₹20 per year, available to all bank account holders aged 18-70.',
    eligibility: 'Savings bank account holders aged 18 to 70 years. Auto-debit must be enabled.',
    documents: 'Aadhaar Card, Bank Passbook, PMSBY consent form',
    benefits: '₹2 lakh for accidental death or permanent disability, ₹1 lakh for partial disability.',
    lastDate: 'Enroll before May 31 each year',
    applyLink: 'https://www.jansuraksha.gov.in/',
    helpline: '180018011125',
    steps: [
      'Visit your bank branch with Aadhaar and passbook',
      'Fill the PMSBY consent form for auto-debit',
      'Premium of ₹20 auto-debited from account each year',
      '₹2 lakh paid in case of accidental death or full disability',
      'Claim through bank with FIR and hospital reports',
    ],
    tags: ['Insurance', 'Accident Cover', 'Low Premium'],
  },
  {
    id: 'pmay',
    title: 'PM Awas Yojana (Housing for All)',
    title_te: 'పీఎం ఆవాస్ యోజన',
    title_hi: 'पीएम आवास योजना',
    category: 'Housing',
    description: 'Central scheme providing interest subsidy on home loans for economically weaker and low-income groups to buy or build a house.',
    eligibility: 'Families with annual income up to ₹6 lakh (EWS/LIG). No prior pucca house ownership.',
    documents: 'Aadhaar Card, Income Certificate, Bank Passbook, Caste Certificate',
    benefits: 'Interest subsidy up to ₹2.67 lakh on home loans up to 20 years tenure.',
    lastDate: 'Ongoing (apply through banks)',
    applyLink: 'https://pmaymis.gov.in/',
    helpline: '1800113377',
    steps: [
      'Check eligibility on pmaymis.gov.in using Aadhaar',
      'Apply through your bank for a home loan with PMAY benefit',
      'Bank verifies income and documents',
      'Interest subsidy credited upfront to loan account',
      'EMI reduced by subsidy amount',
    ],
    tags: ['Housing', 'Home Loan', 'Subsidy'],
  },
];

export const SCHEME_CATEGORIES = [
  'All', 'Agriculture', 'Women Welfare', 'Housing', 'Healthcare',
  'Scholarships', 'Pension Schemes', 'Employment', 'Insurance',
];

export const EMERGENCY_CONTACTS: EmergencyContact[] = [
  { id: 'police', name: 'Police Station', name_te: 'పోలీస్ స్టేషన్', name_hi: 'पुलिस स्टेशन', number: '100', icon: 'Shield', color: 'govt' },
  { id: 'fire', name: 'Fire Station', name_te: 'ఫైర్ స్టేషన్', name_hi: 'फायर स्टेशन', number: '101', icon: 'Flame', color: 'saffron' },
  { id: 'ambulance', name: 'Ambulance', name_te: 'అంబులెన్స్', name_hi: 'एम्बुलेंस', number: '108', icon: 'Ambulance', color: 'red' },
  { id: 'women', name: 'Women Helpline', name_te: 'మహిళల హెల్ప్‌లైన్', name_hi: 'महिला हेल्पलाइन', number: '1091', icon: 'HeartHandshake', color: 'pink' },
  { id: 'child', name: 'Child Helpline', name_te: 'చైల్డ్ హెల్ప్‌లైన్', name_hi: 'बाल हेल्पलाइन', number: '1098', icon: 'Baby', color: 'brand' },
  { id: 'electricity', name: 'Electricity Office (APSPDCL)', name_te: 'విద్యుత్ కార్యాలయం', name_hi: 'बिजली कार्यालय', number: '1912', icon: 'Zap', color: 'amber' },
  { id: 'water', name: 'Water Department', name_te: 'నీటి శాఖ', name_hi: 'जल विभाग', number: '08676-234567', icon: 'Droplets', color: 'blue' },
  { id: 'hospital', name: 'PHC / Hospital', name_te: 'ప్రాథమిక ఆరోగ్య కేంద్రం', name_hi: 'प्राथमिक स्वास्थ्य केंद्र', number: '104', icon: 'Stethoscope', color: 'teal' },
];

export const SCHOOLS: SchoolInfo[] = [
  { name: 'Zilla Parishad High School', type: 'Government School', address: 'Main Road, Gudlavalleru', classes: '6th - 10th Class' },
  { name: 'Mandal Parishad Elementary School', type: 'Government School', address: 'Ward 1, Gudlavalleru', classes: '1st - 5th Class' },
  { name: 'SRK Institute of Sciences', type: 'Degree College', address: 'Gudlavalleru', classes: 'UG & PG Courses' },
  { name: 'SRK College of Engineering', type: 'Engineering College', address: 'Gudlavalleru', classes: 'B.Tech / M.Tech' },
  { name: 'Govt. Junior College', type: 'Junior College', address: 'Near Bus Stand, Gudlavalleru', classes: 'Intermediate (11th-12th)' },
  { name: 'Sri Chaitanya Techno School', type: 'Private School', address: 'Gudlavalleru', classes: 'Nursery - 10th Class' },
  { name: 'Anganwadi Center - Ward 1', type: 'Anganwadi', address: 'Ward 1, Gudlavalleru', classes: '3-6 Years' },
  { name: 'Anganwadi Center - Ward 3', type: 'Anganwadi', address: 'Ward 3, Gudlavalleru', classes: '3-6 Years' },
];

export const TOURIST_PLACES: TouristPlace[] = [
  {
    name: 'Pamarru Sri Lakshmi Narasimha Swamy Temple',
    name_te: 'పమర్రు శ్రీ లక్ష్మీ నరసింహ స్వామి దేవాలయం',
    description: 'A historic temple dedicated to Lord Narasimha, located in nearby Pamarru. Known for its annual festival and beautiful architecture.',
    distance: '5 km from Gudlavalleru',
    category: 'Temple',
    image: 'https://images.pexels.com/photos/15655443/pexels-photo-15655443.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    name: 'Gudivada Town & Markets',
    name_te: 'గుడివాడ పట్టణం',
    description: 'A nearby major town with bustling markets, the famous Karunapani Museum, and rail connectivity to Vijayawada.',
    distance: '12 km from Gudlavalleru',
    category: 'Town',
    image: 'https://images.pexels.com/photos/36848899/pexels-photo-36848899.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    name: 'Vijayawada - Kanaka Durga Temple',
    name_te: 'విజయవాడ - కనకదుర్గ దేవాలయం',
    description: 'The famous temple of Goddess Kanaka Durga on Indrakeeladri hill beside the Krishna River, one of the most visited temples in Andhra Pradesh.',
    distance: '45 km from Gudlavalleru',
    category: 'Temple',
    image: 'https://images.pexels.com/photos/5138790/pexels-photo-5138790.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    name: 'Manginapudi Beach',
    name_te: 'మంగినపూడి బీచ్',
    description: 'A serene beach near Machilipatnam with black soil and a historic Dutch port. Famous for the Magha Pournami bath and seafood.',
    distance: '35 km from Gudlavalleru',
    category: 'Beach',
    image: 'https://images.pexels.com/photos/13061058/pexels-photo-13061058.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    name: 'Kuchipudi Village',
    name_te: 'కూచిపూడి గ్రామం',
    description: 'The birthplace of the classical Kuchipudi dance form, with a dance academy and Siddhendra Yogi statue. A cultural heritage site.',
    distance: '15 km from Gudlavalleru',
    category: 'Heritage',
    image: 'https://images.pexels.com/photos/3913942/pexels-photo-3913942.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    name: 'Krishna River & Canals',
    name_te: 'కృష్ణా నది మరియు కాలువలు',
    description: 'The fertile Krishna delta with its network of irrigation canals — a lifeline for the region\'s agriculture and a peaceful spot for visitors.',
    distance: '20 km from Gudlavalleru',
    category: 'Nature',
    image: 'https://images.pexels.com/photos/14814910/pexels-photo-14814910.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
];

export const COMPLAINT_CATEGORIES = [
  { value: 'Water Problem', label_te: 'నీటి సమస్య', label_hi: 'पानी की समस्या', icon: 'Droplets', sla: '48 hours', priority: 'High' },
  { value: 'Drainage', label_te: 'మురుగునీటి', label_hi: 'नाला', icon: 'Waves', sla: '72 hours', priority: 'High' },
  { value: 'Roads', label_te: 'రోడ్లు', label_hi: 'सड़कें', icon: 'Construction', sla: '7 days', priority: 'Medium' },
  { value: 'Electricity', label_te: 'విద్యుత్', label_hi: 'बिजली', icon: 'Zap', sla: '24 hours', priority: 'High' },
  { value: 'Street Lights', label_te: 'స్ట్రీట్ లైట్లు', label_hi: 'स्ट्रीट लाइट', icon: 'Lightbulb', sla: '48 hours', priority: 'Medium' },
  { value: 'Garbage', label_te: 'చెత్త', label_hi: 'कचरा', icon: 'Trash2', sla: '24 hours', priority: 'Medium' },
  { value: 'Sanitation', label_te: 'పారిశుద్యం', label_hi: 'स्वच्छता', icon: 'Sparkles', sla: '48 hours', priority: 'High' },
  { value: 'Public Property Damage', label_te: 'ప్రభుత్వ ఆస్తి నష్టం', label_hi: 'सरकारी संपत्ति क्षति', icon: 'AlertTriangle', sla: '5 days', priority: 'Medium' },
  { value: 'Animal Nuisance', label_te: 'జంతువుల సమస్య', label_hi: 'जानवरों की समस्या', icon: 'Dog', sla: '72 hours', priority: 'Low' },
  { value: 'Trees & Parks', label_te: 'చెట్లు & పార్కులు', label_hi: 'पेड़ और पार्क', icon: 'TreePine', sla: '5 days', priority: 'Low' },
];

export const COMPLAINT_FAQ = [
  {
    q: 'How long does it take to resolve a complaint?',
    q_te: 'ఫిర్యాదును పరిష్కరించడానికి ఎంత సమయం పడుతుంది?',
    a: 'Most complaints are resolved within 24-72 hours depending on category. Urgent issues like electricity and water are prioritized. You can track the status anytime using your ticket number.',
    a_te: 'చాలా ఫిర్యాదులు 24-72 గంటలలో పరిష్కరించబడతాయి. విద్యుత్, నీటి సమస్యలకు ప్రాధాన్యత ఇవ్వబడుతుంది. మీ టికెట్ నంబర్‌తో ఎప్పుడైనా ట్రాక్ చేయవచ్చు.',
  },
  {
    q: 'What should I do if my complaint is not resolved?',
    q_te: 'నా ఫిర్యాదు పరిష్కరించబడనిట్లయితే ఏమి చేయాలి?',
    a: 'If your complaint is pending beyond the expected time, you can escalate by calling the Panchayat Office at 08676-234567 or visiting in person during office hours (9:30 AM - 5:00 PM).',
    a_te: 'మీ ఫిర్యాదు ఆలస్యం అయితే, పంచాయతీ కార్యాలయానికి కాల్ చేయండి లేదా వ్యక్తిగతంగా వెళ్ళండి.',
  },
  {
    q: 'Can I submit a complaint anonymously?',
    q_te: 'అజ్ఞాతంగా ఫిర్యాదు చేయవచ్చా?',
    a: 'No, you need to provide your name and mobile number so we can contact you for updates and verification. Your personal information is kept confidential and not shared publicly.',
    a_te: 'కాదు, మీ పేరు మరియు మొబైల్ నంబర్ అవసరం. మీ సమాచారం రహస్యంగా ఉంచబడుతుంది.',
  },
  {
    q: 'What happens after I submit a complaint?',
    q_te: 'ఫిర్యాదు దాఖలు చేసిన తర్వాత ఏమి జరుగుతుంది?',
    a: 'You receive a unique ticket number immediately. The complaint is assigned to the concerned department. You can track progress: Pending → In Progress → Completed. SMS updates may be sent to your mobile.',
    a_te: 'వెంటనే టికెట్ నంబర్ లభిస్తుంది. ఫిర్యాదు సంబంధిత విభాగానికి అప్పగించబడుతుంది.',
  },
];

export const VILLAGE_AREAS = [
  'Main Road', 'Ward 1', 'Ward 2', 'Ward 3', 'Colony Area', 'Near Bus Stand',
  'Near Railway Station', 'Market Area', 'School Area', 'Temple Street',
];

export const CERTIFICATES: CertificateService[] = [
  {
    name: 'Birth Certificate', name_te: 'జనన ధృవీకరణ పత్రం', name_hi: 'जन्म प्रमाण पत्र',
    icon: 'Baby', link: 'https://cr.ap.gov.in/',
    desc: 'Register and download birth certificates for newborns.',
    desc_te: 'నవజాత శిశువుల జనన ధృవీకరణ పత్రం నమోదు చేయండి.',
    desc_hi: 'नवजात शिशुओं के जन्म प्रमाण पत्र दर्ज करें।',
    documents: 'Hospital birth report, Parents Aadhaar, Address proof',
    fee: '₹20 (first copy), ₹10 (extra copy)',
    processingTime: '7-15 days',
    onlineAvailable: true, offlineAvailable: true,
  },
  {
    name: 'Death Certificate', name_te: 'ృత్యు ధృవీకరణ పత్రం', name_hi: 'मृत्यु प्रमाण पत्र',
    icon: 'FileText', link: 'https://cr.ap.gov.in/',
    desc: 'Obtain death certificates for registered deaths.',
    desc_te: 'నమోదైన మరణాల ధృవీకరణ పత్రం పొందండి.',
    desc_hi: 'दर्ज किए गए मृत्यु प्रमाण पत्र प्राप्त करें।',
    documents: 'Hospital/doctor death report, Aadhaar of deceased, Address proof',
    fee: '₹20 (first copy), ₹10 (extra copy)',
    processingTime: '7-15 days',
    onlineAvailable: true, offlineAvailable: true,
  },
  {
    name: 'Income Certificate', name_te: 'ఆదాయ ధృవీకరణ పత్రం', name_hi: 'आय प्रमाण पत्र',
    icon: 'Wallet', link: 'https://gramasachivalayam.ap.gov.in/',
    desc: 'Proof of family income for scheme eligibility.',
    desc_te: 'పథకాల అర్హత కోసం కుటుంబ ఆదాయ ధృవీకరణ పత్రం.',
    desc_hi: 'योजना पात्रता के लिए पारिवारिक आय प्रमाण पत्र।',
    documents: 'Aadhaar, Ration Card, Salary slip/IT return, Land records',
    fee: 'Free',
    processingTime: '7 working days',
    onlineAvailable: true, offlineAvailable: true,
  },
  {
    name: 'Caste Certificate', name_te: 'కుల ధృవీకరణ పత్రం', name_hi: 'जाति प्रमाण पत्र',
    icon: 'ScrollText', link: 'https://gramasachivalayam.ap.gov.in/',
    desc: 'Official caste category certificate for reservations and schemes.',
    desc_te: 'రిజర్వేషన్ కోసం అధికారిక కుల ధృవీకరణ పత్రం.',
    desc_hi: 'आरक्षण के लिए आधिकारिक जाति प्रमाण पत्र।',
    documents: 'Aadhaar, Ration Card, Parent caste certificate, School TC',
    fee: 'Free',
    processingTime: '15 working days',
    onlineAvailable: true, offlineAvailable: true,
  },
  {
    name: 'Residence Certificate', name_te: 'నివాస ధృవీకరణ పత్రం', name_hi: 'निवास प्रमाण पत्र',
    icon: 'Home', link: 'https://gramasachivalayam.ap.gov.in/',
    desc: 'Proof of residence in Gudlavalleru / Andhra Pradesh.',
    desc_te: 'గుడ్లవల్లేరు / ఆంధ్రప్రదేశ్‌లో నివాస ధృవీకరణ.',
    desc_hi: 'गुडलवल्लेरु / आंध्र प्रदेश में निवास प्रमाण।',
    documents: 'Aadhaar, Ration Card, Voter ID, Utility bill',
    fee: 'Free',
    processingTime: '7 working days',
    onlineAvailable: true, offlineAvailable: true,
  },
  {
    name: 'Aadhaar Services', name_te: 'ఆధార్ సేవలు', name_hi: 'आधार सेवाएँ',
    icon: 'Fingerprint', link: 'https://uidai.gov.in/',
    desc: 'Aadhaar enrollment, update, and linking services.',
    desc_te: 'ఆధార్ నమోదు, అప్‌డేట్, లింక్ సేవలు.',
    desc_hi: 'आधार नामांकन, अपडेट, लिंक सेवाएँ।',
    documents: 'Existing Aadhaar (for updates), Address proof, ID proof',
    fee: 'Free (enrollment), ₹50 (update)',
    processingTime: '90 days for new, 7-30 days for updates',
    onlineAvailable: false, offlineAvailable: true,
  },
  {
    name: 'Voter Services', name_te: 'ఓటర్ సేవలు', name_hi: 'मतदाता सेवाएँ',
    icon: 'Vote', link: 'https://voterportal.eci.gov.in/',
    desc: 'Voter ID registration, correction, and download.',
    desc_te: 'ఓటర్ ID నమోదు, సవరణ, డౌన్‌లోడ్.',
    desc_hi: 'वोटर ID पंजीकरण, सुधार, डाउनलोड।',
    documents: 'Aadhaar, Address proof, Age proof, Passport photo',
    fee: 'Free',
    processingTime: '30-45 days',
    onlineAvailable: true, offlineAvailable: true,
  },
  {
    name: 'Ration Card', name_te: 'రేషన్ కార్డ్', name_hi: 'राशन कार्ड',
    icon: 'ShoppingBasket', link: 'https://epdsap.ap.gov.in/',
    desc: 'Apply for new ration card or modify existing.',
    desc_te: 'కొత్త రేషన్ కార్డ్ కోసం దరఖాస్తు.',
    desc_hi: 'नया राशन कार्ड के लिए आवेदन।',
    documents: 'Aadhaar of all members, Address proof, Income certificate, Photo',
    fee: '₹25 (new), ₹10 (modification)',
    processingTime: '30 days',
    onlineAvailable: true, offlineAvailable: true,
  },
  {
    name: 'Property Tax Payment', name_te: 'ప్రాపర్టీ ట్యాక్స్', name_hi: 'संपत्ति कर',
    icon: 'ReceiptIndianRupee', link: 'https://cdma.ap.gov.in/',
    desc: 'Pay annual property/house tax to the Panchayat.',
    desc_te: 'పంచాయతీకి వార్షిక ప్రాపర్టీ ట్యాక్స్ చెల్లించండి.',
    desc_hi: 'पंचायत को वार्षिक संपत्ति कर का भुगतान करें।',
    documents: 'Property assessment number, Owner Aadhaar',
    fee: 'As per property assessment',
    processingTime: 'Instant receipt',
    onlineAvailable: true, offlineAvailable: true,
  },
  {
    name: 'Building Permission', name_te: 'భవన అనుమతి', name_hi: 'भवन अनुमति',
    icon: 'Building2', link: 'https://gramasachivalayam.ap.gov.in/',
    desc: 'Apply for permission to construct or modify buildings.',
    desc_te: 'భవన నిర్మాణ లేదా మార్పు అనుమతి.',
    desc_hi: 'भवन निर्माण या संशोधन अनुमति।',
    documents: 'Land documents, Site plan, Aadhaar, Building plan',
    fee: 'As per built-up area (varies)',
    processingTime: '30 days',
    onlineAvailable: false, offlineAvailable: true,
  },
  {
    name: 'Old Age Pension', name_te: 'వృద్ధాప్య పింఛన్', name_hi: 'वृद्धावस्था पेंशन',
    icon: 'HandCoins', link: 'https://gramasachivalayam.ap.gov.in/',
    desc: 'Apply for monthly old age pension (₹3,000/month).',
    desc_te: 'నెలవారీ వృద్ధాప్య పింఛన్ (₹3,000/నెల).',
    desc_hi: 'मासिक वृद्धावस्था पेंशन (₹3,000/माह)।',
    documents: 'Aadhaar, Age proof (60+), Income certificate, Bank passbook',
    fee: 'Free',
    processingTime: '30-45 days',
    onlineAvailable: false, offlineAvailable: true,
  },
  {
    name: 'Passport Application', name_te: 'పాస్‌పోర్ట్ దరఖాస్తు', name_hi: 'पासपोर्ट आवेदन',
    icon: 'BookUser', link: 'https://www.passportindia.gov.in/',
    desc: 'Fresh passport application or renewal.',
    desc_te: 'కొత్త పాస్‌పోర్ట్ దరఖాస్తు లేదా రెన్యూవల్.',
    desc_hi: 'नया पासपोर्ट आवेदन या नवीनीकरण।',
    documents: 'Aadhaar, Birth certificate, Address proof, Education proof',
    fee: '₹1,500 (36 pages), ₹2,000 (60 pages)',
    processingTime: '30-45 days',
    onlineAvailable: true, offlineAvailable: false,
  },
];

export const QUICK_STATS = [
  { label: 'Population', label_te: 'జనాభా', label_hi: 'जनसंख्या', value: '11,400+', icon: 'Users' },
  { label: 'Literacy', label_te: 'అక్షరాస్యత', label_hi: 'साक्षरता', value: '78%', icon: 'GraduationCap' },
  { label: 'Pincode', label_te: 'పిన్‌కోడ్', label_hi: 'पिन कोड', value: '521356', icon: 'MapPin' },
  { label: 'Area', label_te: 'విస్తీర్ణం', label_hi: 'क्षेत्रफल', value: '12.5 sq.km', icon: 'LandPlot' },
];

// ─── Agriculture data ───
export const CROP_CALENDAR = [
  { crop: 'Paddy (Kharif)', crop_te: 'వరి (ఖరీఫ్)', season: 'Kharif', months: 'Jun - Nov', sowing: 'June', harvesting: 'Nov', tip: 'Seed rate: 25 kg/acre. Transplant 25-30 day old seedlings.' },
  { crop: 'Paddy (Rabi)', crop_te: 'వరి (రబీ)', season: 'Rabi', months: 'Dec - Apr', sowing: 'December', harvesting: 'April', tip: 'Ensure canal water availability before sowing.' },
  { crop: 'Black Gram', crop_te: 'మినుము', season: 'Rabi', months: 'Nov - Feb', sowing: 'November', harvesting: 'February', tip: 'Good as post-paddy crop. Seed rate: 8 kg/acre.' },
  { crop: 'Green Gram', crop_te: 'పెసర', season: 'Kharif', months: 'Jun - Sep', sowing: 'June', harvesting: 'September', tip: 'Short duration 60-70 days. Seed rate: 10 kg/acre.' },
  { crop: 'Sugarcane', crop_te: 'చెరకు', season: 'Annual', months: 'Year-round', sowing: 'Any month', harvesting: '14-16 months', tip: 'Plant setts at 40,000/acre. Needs regular irrigation.' },
  { crop: 'Vegetables', crop_te: 'కూరగాయలు', season: 'Both', months: 'Year-round', sowing: 'Any month', harvesting: '45-90 days', tip: 'Use drip irrigation. High market demand locally.' },
  { crop: 'Coconut', crop_te: 'కొబ్బరి', season: 'Perennial', months: 'Year-round', sowing: 'Monsoon', harvesting: 'Every 60 days', tip: 'Apply 1kg urea + 1kg MOP per palm per year.' },
  { crop: 'Mango', crop_te: 'మామిడి', season: 'Perennial', months: 'Mar - Jun', sowing: 'Jul - Aug', harvesting: 'Mar - Jun', tip: 'Prune after harvest. Apply FYM in December.' },
];

export const AGRI_RESOURCES = [
  { name: 'Rythu Bharosa Kendram (RBK) - Gudlavalleru', type: 'Seed & Fertilizer Center', contact: '08676-234567', hours: '9 AM - 5 PM', desc: 'Buy quality seeds, fertilizers, pesticides at subsidized rates. Also provides soil testing and machinery rental.' },
  { name: 'Krishi Vigyan Kendra (KVK) - Gudivada', type: 'Agricultural Extension', contact: '08674-245000', hours: '9 AM - 5 PM', desc: 'Training programs, demonstrations, soil testing, and technical guidance from agricultural scientists.' },
  { name: 'Gudivada Market Yard', type: 'Produce Market', contact: '08674-246000', hours: '6 AM - 6 PM', desc: 'Mandi for selling paddy, pulses, and sugarcane at MSP. Check daily rates before harvest.' },
  { name: 'AP Cooperative Bank - Gudlavalleru', type: 'Crop Loans', contact: '08676-234567', hours: '10 AM - 4 PM', desc: 'Crop loans, Kisan Credit Card, and agricultural term loans at subsidized interest rates.' },
  { name: 'Veterinary Hospital - Gudlavalleru', type: 'Livestock Care', contact: '08676-234567', hours: '9 AM - 4 PM', desc: 'Treatment, vaccination, artificial insemination for cattle, buffalo, sheep, and poultry.' },
];

export const PEST_ALERTS = [
  { pest: 'Stem Borer (నత్తి పురుగు)', crop: 'Paddy', severity: 'High', season: 'Jul - Sep', symptom: 'Dead heart in tillers, white ears in panicle stage', remedy: 'Apply Chlorantraniliprole 0.4% GR at 10 kg/acre or spray Cartap 50 SP at 400g/acre.' },
  { pest: 'Leaf Folder (ఆకుముడత పురుగు)', crop: 'Paddy', severity: 'Medium', season: 'Aug - Oct', symptom: 'Leaves folded longitudinally and eaten inside', remedy: 'Spray Dichlorvos 76 EC at 250 ml/acre or use light traps.' },
  { pest: 'Blast Disease (బంగారు ఆకుమచ్చ)', crop: 'Paddy', severity: 'High', season: 'Sep - Nov', symptom: 'Diamond-shaped spots on leaves, neck rot', remedy: 'Spray Tricyclazole 75 WP at 100g/acre. Use resistant varieties like BPT-5204.' },
  { pest: 'Aphids (ఆఫిడ్స్)', crop: 'Black Gram', severity: 'Medium', season: 'Dec - Jan', symptom: 'Curling leaves, sticky honeydew, stunted growth', remedy: 'Spray Imidacloprid 200 SL at 100 ml/acre or Neem oil 5%.' },
  { pest: 'Red Hairy Caterpillar', crop: 'All crops', severity: 'Low', season: 'Jun - Aug', symptom: 'Defoliation of leaves, clustering on stems', remedy: 'Deep ploughing in summer, light traps, spray Quinalphos.' },
];

export const GOVT_AGRI_SUBSIDIES = [
  { name: 'PM Fasal Bima Yojana (Crop Insurance)', subsidy: 'Premium only 2% (Kharif), 1.5% (Rabi)', desc: 'Insurance against crop loss due to drought, flood, pest attack. Apply through bank or RBK.' },
  { name: 'Drip Irrigation Subsidy', subsidy: 'Up to 90% of cost', desc: 'Micro-irrigation systems for water-saving. Apply at Horticulture Department or RBK.' },
  { name: 'Tractor & Farm Equipment', subsidy: '25-50% subsidy', desc: 'Subsidized tractors, rotavators, harvesters. SC/ST farmers get higher subsidy.' },
  { name: 'Organic Farming (PKVY)', subsidy: '₹50,000/hectare (3 years)', desc: 'Promote organic farming clusters. Apply through Agriculture Officer.' },
  { name: 'Kisan Credit Card (KCC)', subsidy: 'Interest subvention 2% + prompt repayment 3%', desc: 'ATM-cum-debit card for crop loans up to ₹3 lakh. Apply at your bank.' },
  { name: 'Solar Pump Set', subsidy: 'Up to 60% subsidy', desc: 'Replace diesel pumps with solar. Apply at NREDCAP or RBK.' },
];

// ─── Health data ───
export const IMMUNIZATION_SCHEDULE = [
  { age: 'At Birth', vaccines: 'BCG, OPV-0, Hep-B1', diseases: 'Tuberculosis, Polio, Hepatitis B' },
  { age: '6 Weeks', vaccines: 'OPV-1, Pentavalent-1, Rotavirus-1, PCV-1', diseases: 'Polio, DTP, Hep-B, Hib, Rotavirus, Pneumonia' },
  { age: '10 Weeks', vaccines: 'OPV-2, Pentavalent-2, Rotavirus-2, PCV-2', diseases: 'Polio, DTP, Hep-B, Hib, Rotavirus, Pneumonia' },
  { age: '14 Weeks', vaccines: 'OPV-3, Pentavalent-3, Rotavirus-3, PCV-3', diseases: 'Polio, DTP, Hep-B, Hib, Rotavirus, Pneumonia' },
  { age: '9-12 Months', vaccines: 'MR-1 (Measles-Rubella)', diseases: 'Measles, Rubella' },
  { age: '16-18 Months', vaccines: 'MR-2, DPT Booster, OPV Booster', diseases: 'Measles, Rubella, DTP, Polio' },
  { age: '5-6 Years', vaccines: 'DPT Booster-2', diseases: 'Diphtheria, Tetanus, Pertussis' },
  { age: '10-16 Years', vaccines: 'TD Vaccine', diseases: 'Tetanus, Diphtheria' },
  { age: 'Pregnant Women', vaccines: 'TT (2 doses), IFA tablets', diseases: 'Tetanus for mother & baby' },
];

export const HEALTH_TIPS = [
  { title: 'Clean Drinking Water', title_te: 'శుద్ధమైన త్రాగునీరు', icon: 'Droplet', tip: 'Always drink boiled or filtered water. Chlorinate wells during monsoon to prevent waterborne diseases like cholera and typhoid.' },
  { title: 'Mosquito Prevention', title_te: 'దోమల నివారణ', icon: 'Bug', tip: 'Remove stagnant water around your home. Use mosquito nets while sleeping. Apply repellent during evening hours to prevent dengue and malaria.' },
  { title: 'Maternal Care', title_te: 'గర్భిణీ సంరక్షణ', icon: 'HeartHandshake', tip: 'Register pregnancy at PHC early. Take IFA tablets daily. Have at least 4 ANC check-ups. Institutional delivery is free under Aarogyasri.' },
  { title: 'Child Nutrition', title_te: 'పిల్లల పోషణ', icon: 'Baby', tip: 'Exclusive breastfeeding for 6 months. Introduce complementary foods after 6 months. Take child to Anganwadi for growth monitoring and supplements.' },
  { title: 'Hypertension & Diabetes', title_te: 'రక్తపోటు & మధుమేహం', icon: 'Activity', tip: 'Free BP and blood sugar check at PHC every Tuesday. Walk 30 min daily. Reduce salt and sugar intake. Take medicines regularly.' },
  { title: 'Mental Health', title_te: 'మానసిక ఆరోగ్యం', icon: 'Brain', tip: 'Mental health support is available at District Hospital. Call KIRAN helpline 1800-599-0019 for free counseling. No stigma — seek help.' },
];

export const AAROGYASRI_INFO = {
  title: 'YSR Aarogyasri',
  coverage: 'Up to ₹5 lakh per family per year',
  procedures: '2,000+ medical and surgical procedures',
  hospitals: '1,000+ empanelled hospitals across AP & Telangana',
  cost: 'Completely free — no out-of-pocket expenses',
  enrollment: 'Enroll at Grama Sachivalayam with White Ration Card & Aadhaar',
  helpline: '1900',
  coveredTreatments: [
    'Cardiac surgeries (bypass, angioplasty)',
    'Cancer treatment (chemotherapy, radiotherapy, surgery)',
    'Kidney transplantation & dialysis',
    'Neuro-surgery & trauma care',
    'Neonatal intensive care (NICU)',
    'Joint replacement & orthopedic surgery',
    'Burns management',
    'COVID-19 treatment (when applicable)',
  ],
};

export const TELEMEDICINE_INFO = {
  title: 'Telemedicine & e-Sanjeevani',
  desc: 'Free doctor consultation from your phone or computer. Talk to a specialist without traveling to hospital.',
  steps: [
    'Visit esanjeevani.in or download e-Sanjeevani OPD app',
    'Register with your mobile number and Aadhaar',
    'Wait in the virtual queue — average wait 15-20 min',
    'Consult the doctor via video call',
    'Receive e-prescription by SMS/email — take to any pharmacy',
  ],
  helpline: '1800-120-1313',
  hours: '24x7 (doctor availability varies)',
};

// ─── Equipment Rental data ───
export const EQUIPMENT_TYPES = [
  { value: 'Tractor', icon: 'Tractor' },
  { value: 'Rotavator', icon: 'Layers' },
  { value: 'Harvester', icon: 'Wheat' },
  { value: 'Pump Set', icon: 'Droplets' },
  { value: 'Sprayer', icon: 'SprayCan' },
  { value: 'Seed Drill', icon: 'Grid3x3' },
  { value: 'Plough', icon: 'Mountain' },
  { value: 'Thresher', icon: 'Cog' },
  { value: 'Trailer', icon: 'Truck' },
  { value: 'Other', icon: 'Package' },
];

// ─── Waste Management data ───
export const WASTE_TYPES = [
  'Garbage Overflow', 'Drainage Block', 'Open Dumping', 'Plastic Waste',
  'Public Toilet Issue', 'Animal Waste', 'Street Cleaning', 'Other',
];

export const VOLUNTEER_AVAILABILITY = [
  'Weekday Mornings', 'Weekday Evenings', 'Weekends', 'Anytime',
];

export const GARBAGE_SCHEDULE = [
  { day: 'Monday', areas: 'Ward 1-4 · Main Bazaar', time: '6:00 - 8:00 AM' },
  { day: 'Tuesday', areas: 'Ward 5-8 · RTC Road', time: '6:00 - 8:00 AM' },
  { day: 'Wednesday', areas: 'Ward 1-4 · Main Bazaar', time: '6:00 - 8:00 AM' },
  { day: 'Thursday', areas: 'Ward 5-8 · RTC Road', time: '6:00 - 8:00 AM' },
  { day: 'Friday', areas: 'All Wards · Full Village', time: '6:00 - 9:00 AM' },
  { day: 'Saturday', areas: 'Ward 1-4 · Market Area', time: '6:00 - 8:00 AM' },
  { day: 'Sunday', areas: 'Special Drive · All Wards', time: '7:00 - 10:00 AM' },
];

export const RECYCLING_TIPS = [
  { title: 'Segregate at Home', te: 'ఇంట్లోనే వేరు చేయండి', icon: 'Split', desc: 'Use two bins — green for wet waste (food, leaves), blue for dry waste (plastic, paper, glass).', desc_te: 'రెండు బిన్‌లు వాడండి — తడి వ్యర్థానికి పచ్చ, పొడి వ్యర్థానికి నీలం.' },
  { title: 'Compost Kitchen Waste', te: 'వంటగది వ్యర్థాన్ని ఎరువుగా మార్చండి', icon: 'Sprout', desc: 'Turn food scraps and vegetable peels into natural compost for your plants and garden.', desc_te: 'ఆహార వ్యర్థాలను మొక్కలకు సహజ ఎరువుగా మార్చండి.' },
  { title: 'Reduce Plastic Use', te: 'ప్లాస్టిక్ వాడకం తగ్గించండి', icon: 'Recycle', desc: 'Carry cloth bags for shopping. Say no to single-use plastics and plastic covers.', desc_te: 'షాపింగ్‌కు గుడ్డ సంచులు తీసుకెళ్లండి. ఒకసారి వాడే ప్లాస్టిక్‌కు నో చెప్పండి.' },
  { title: 'Reuse & Repurpose', te: 'తిరిగి వాడండి', icon: 'Repeat', desc: 'Reuse glass jars for storage, old clothes as cleaning cloths. Give items a second life.', desc_te: 'గ్లాస్ జాడీలను నిల్వ కోసం వాడండి. పాత బట్టలను తుడుపు గుడ్డలుగా వాడండి.' },
  { title: 'Safe E-Waste Disposal', te: 'ఇ-వేస్ట్ సురక్షితంగా పారవేయండి', icon: 'MonitorSmartphone', desc: 'Drop old phones, batteries, and electronics at the e-waste collection point at Panchayat Office.', desc_te: 'పాత ఫోన్‌లు, బ్యాటరీలను పంచాయతీ కార్యాలయంలో ఇ-వేస్ట్ సేకరణ కేంద్రంలో వదిలివేయండి.' },
  { title: 'Say No to Burning', te: 'కాల్చడానికి లేదు', icon: 'Flame', desc: 'Never burn waste in the open — it releases toxic smoke. Hand it to the collection team.', desc_te: 'వ్యర్థాలను బహిరంగంగా కాల్చకండి — అది విషపూరిత పొగ విడుస్తుంది.' },
];

export const CLEANLINESS_CAMPAIGNS = [
  {
    title: 'Swachh Bharat Sunday Drive',
    te: 'స్వచ్ఛ భారత్ ఆదివారం అభియానం',
    date: 'Every Sunday',
    time: '7:00 - 9:00 AM',
    location: ' Village Center & Main Roads',
    desc: 'Join the weekly cleanliness drive. Volunteers gather at the village center to clean main roads, public spaces, and drains.',
    desc_te: 'వారాంతపు శుభ్రత అభియానంలో పాల్గొనండి. ప్రధాన రహదారులు, బహిరంగ ప్రదేశాలు శుభ్రపరుస్తారు.',
  },
  {
    title: 'Plastic-Free Village Campaign',
    te: 'ప్లాస్టిక్ రహిత గ్రామ అభియానం',
    date: '1st Saturday of every month',
    time: '8:00 - 10:00 AM',
    location: 'All Wards',
    desc: 'Monthly campaign to collect and safely dispose of plastic waste. Cloth bags distributed free to participants.',
    desc_te: 'ప్లాస్టిక్ వ్యర్థాలను సేకరించి సురక్షితంగా పారవేసే నెలవారీ అభియానం. పాల్గొనేవారికి గుడ్డ సంచులు ఉచితం.',
  },
  {
    title: 'Door-to-Door Awareness Drive',
    te: 'తలుపు నుండి తలుపు అవగాహన',
    date: '15th of every month',
    time: '5:00 - 6:00 PM',
    location: 'All Wards',
    desc: 'Volunteers visit homes to educate residents on waste segregation, composting, and sanitation practices.',
    desc_te: 'వ్యర్థ విభజన, ఎరువుగా మార్చడం, పారిశుద్ధ్యం గురించి నివాసితులకు అవగాహన కల్పిస్తారు.',
  },
];

// ─── Notices extra data ───
export const NOTICE_TYPES = [
  'All', 'Circular', 'Tax Notice', 'Tender Notice', 'Meeting Minutes',
  'Public Notice', 'Event Notice', 'Administration',
];
